ProjekatPasos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PrijemniIspit.Models;
using System.Diagnostics;

namespace PrijemniIspit.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Pocetna()
        {
            return View();
        }

        public IActionResult OServisu() 
        {
            return View();
        }

        public IActionResult PrijavaIliRegistracija()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjekatPasos/Controllers/NalogController.cs
using AplikacioniSloj;
using Microsoft.AspNetCore.Mvc;
using SlojPodataka;

public class NalogController : Controller
{
    private readonly clsKorisnikServis _korisnikServis;

    public NalogController(clsKorisnikServis korisnikServis)
    {
        _korisnikServis = korisnikServis;
    }

    [HttpGet]
    public ActionResult Registracija()
    {
        return View();
    }

    [HttpPost]
    public ActionResult Registracija(RegistracijaModel model)
    {
        if (ModelState.IsValid)
        {
            bool uspesnaRegistracija = _korisnikServis.Dodaj(new clsKorisnik
            {
                Jmbg = model.JMBG,
                Ime = model.Ime,
                Prezime = model.Prezime,
                Email = model.Email,
                Lozinka = model.Lozinka
            });

            if (uspesnaRegistracija)
            {
                // Ako je registracija uspešna, preusmerite korisnika na odgovarajući view ili akciju
                return RedirectToAction("Prijava");
            }
            else
            {
                // Ako registracija nije uspela, možete dodati odgovarajuću logiku ili poruku
                ModelState.AddModelError(string.Empty, "Регистрација није успешна. Молимо покушајте поново.");
            }
        }

        // Ako ModelState nije validan, vraća se isti view sa postojećim podacima
        return View(model);
    }

    [HttpGet]
    public ActionResult Prijava()
    {
        return View();
    }
    [HttpPost]
    public ActionResult Prijava(PrijavaModel model)
    {
        if (ModelState.IsValid)
        {
            // Pozovite metodu iz servisa koja proverava korisničke podatke
            var prijavljeniKorisnik = _korisnikServis.PronadjiPoEmail(model.Email);

            if (prijavljeniKorisnik != null)
            {
                // Ako je pronađen korisnik sa datom e-poštom, proverite lozinku
                if (prijavljeniKorisnik.Lozinka == model.Lozinka)
                {
                    // Lozinka je ispravna, postavite korisničke podatke u sesiju
                    HttpContext.Session.SetString("JMBG", prijavljeniKorisnik.Jmbg);
                    HttpContext.Session.SetString("Ime", prijavljeniKorisnik.Ime);
                    HttpContext.Session.SetString("Prezime", prijavljeniKorisnik.Prezime);
                    HttpContext.Session.SetString("Email", prijavljeniKorisnik.Email);
                    HttpContext.Session.SetString("Lozinka", prijavljeniKorisnik.Lozinka);
                    HttpContext.Session.SetString("TipKorisnika", prijavljeniKorisnik.TipKorisnika);

                    // Redirekcija na odgovarajući view u zavisnosti od tipa korisnika
                    if (prijavljeniKorisnik.TipKorisnika == "admin")
                    {
                        return RedirectToAction("AdminPocetna", "Admin");
                    }
                    else if (prijavljeniKorisnik.TipKorisnika == "student")
                    {
                        return RedirectToAction("KorisnikPocetna", "Korisnik");
                    }
                }
                else
                {
                    // Pogrešna lozinka
                    ModelState.AddModelError(string.Empty, "Погрешна лозинка");
                }
            }
            else
            {
                // Nema korisnika sa datom e-poštom
                ModelState.AddModelError(string.Empty, "Нема корисника у бази података са тим имејлом!");
            }
        }

        // Ako ModelState nije validan, vraća se isti view sa postojećim podacima
        return View(model);
    }

}

ProjekatPasos/Views/Home/OServisu.cshtml
@{
    ViewData["Title"] = "О сервису";
}
<h1 class="display-3">@ViewData["Title"]</h1>

<div class="container-fluid">
<p> Сервис за пријаву и полагање пријемног испита је интернет сервис који омогућава студентима да се региструју, пријаве на испит, и прате своје резултате.
    Уколико комисија утврди да студент испуњава услове за полагање испита, исти ће бити обавештен о термину одржавања испита.
</p>
</div>

ProjekatPasos/Views/Home/Pocetna.cshtml
@{
    ViewData["Title"] = "Почетна";
}

<div class="text-center">
    <h1 class="display-3">ДОБРОДОШЛИ,</h1>
    <h2 class="display-3">улогујте се и брзо закажите свој пријемни испит.</h2>
    <h3>Региструјте се, пријавите се, закажите испит и пратите своје резултате.</h3>
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PrijavaIliRegistracija"><button class="mojeDuge">ПРИЈАВИ СЕ</button></a>
</div>

ProjekatPasos/Views/Home/PrijavaIliRegistracija.cshtml
@{
    ViewData["Title"] = "Пријава или регистрација";
}

<div class="text-center">
    <p class="display-1">Уколико већ имате налог пријавите се, уколико немате региструјте се!</p>
   <div class="d-inline-flex"> 
       <a class="nav-link text-dark" asp-area="" asp-controller="Nalog" asp-action="Prijava"><button>ПРИЈАВИ СЕ</button></a>
       <a class="nav-link text-dark" asp-area="" asp-controller="Nalog" asp-action="Registracija"><button>РЕГИСТРУЈ СЕ</button></a>
    </div>
</div>